### ISSUE TITLE
fblock ERROR: Can't open framebuffer. Permission denied

### ISSUE THREAD

**Issue by ghost** [kevinboone/fbclock#3]
See title

**Comment by kevinboone** [comment]
This is a normal finding if you're running as a user that doesn't have write access to the framebuffer device. On my Fedora system I have:

$ ls -l /dev/fb0 
crw-rw----. 1 root video 29, 0 Apr  8 09:23 /dev/fb0

To write to the framebuffer I'd have to be root, or a user that is a member of the 'video' group. Different Linux systems arrange these things in different ways. Have you checked your user permissions?

**Comment by ghost** [comment]
Fixed! I just ran `sudo usermod -a -G video ******` to change add myself to the `video` group. Thanks!
